services:
  database_mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - todo-network
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
      build: backend
      networks:
        - todo-network
      depends_on:
        database_mysql:
          condition: service_healthy
      ports:
        - "3000:3000"
      expose:
        - 3000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 30s
        timeout: 10s
        retries: 5
  frontend:
      build: frontend
      networks:
        - todo-network
      depends_on:
        backend:
          condition: service_healthy
      ports:
        - "3009:80"
networks:
  todo-network: {}
